version: '2'
services:
    trafix:
        image: ramazanfirin/trafix:test_001
        environment:
            - SPRING_PROFILES_ACTIVE=dev,swagger
            #- EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            #- SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://89.19.30.126:3306/u0221508_trafix?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATASOURCE_USERNAME=u0221508_ramazan
            - SPRING_DATASOURCE_PASSWORD=ra5699mo
            - APPLICATION_FTPDIRECTORY=/ftpDirectory
            - JHIPSTER_SLEEP=5 # gives time for the JHipster Registry to boot before the application
        volumes:
            - /home/ramazan/Desktop:/ftpDirectory
        ports:
            - 8080:8080