version: '2'
services:
    trafix:
        image: ramazanfirin/trafix:test_0.0.2
        environment:
            - SPRING_PROFILES_ACTIVE=dev,swagger
            #- EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            #- SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            #- SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/trafficanalzyzerv2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/trafix?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATASOURCE_USERNAME=root
            #- SPRING_DATASOURCE_PASSWORD=ra5699mo
            - SPRING_DATASOURCE_PASSWORD=trafix
            - APPLICATION_FTPDIRECTORY=/ftpDirectory
            - APPLICATION_AISCRIPTPATH=/aiScriptPath
            - APPLICATION_AISCRIPTNAME=pipeline.py
            - JHIPSTER_SLEEP=5 # gives time for the JHipster Registry to boot before the application
            - aiScriptEndpoint=http://localhost:8088
            - reportInterval=2
        volumes:
            - /ftpDirectory:/ftpDirectory
        ports:
            - 8080:8080
        network_mode: host

    apache:
        image: 'bitnami/apache:latest'
        ports:
            - 8000:8080
            - 443:8443
        volumes:
            - /ftpDirectory:/app        

