version: '2'

services:

  mysql:
    image: mariadb:10.1.19
    #image: mysql:8
    command: --default-authentication-plugin=mysql_native_password 
    ports:
      - 3306:3306
    volumes:
      #- ./mysql3:/var/lib/mysql
      - ${HOME}/mysql4:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: trafix
